%YAML:1.0
---
model_type: PINHOLE
camera_name: camera
image_width: 512
image_height: 512
distortion_parameters:
   k1: 0.0
   k2: 0.0
   p1: 0.0
   p2: 0.0
projection_parameters:
   fx: 217.03269213
   fy: 217.03269213
   cx: 267.19477463
   cy:  99.35049158
